create sequence hibernate_sequence start with 1 increment by 1;
create table roadmap (id varchar(255) not null, description varchar(255), name varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table roadmap (id varchar(255) not null, description varchar(255), name varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table roadmap (id varchar(255) not null, description varchar(255), name varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table roadmap (id varchar(255) not null, description varchar(255), name varchar(255), primary key (id));
create table topics (id varchar(255) not null, description varchar(255), name varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table answer (id varchar(255) not null, description varchar(255), name varchar(255), primary key (id));
create table question (id varchar(255) not null, created_at varchar(255), deleted varchar(255), description varchar(255), name varchar(255), status varchar(255), updated_at varchar(255), primary key (id));
create table roadmap (id varchar(255) not null, description varchar(255), name varchar(255), primary key (id));
create table roadmap_topics (roadmap_id varchar(255) not null, topics_id varchar(255) not null);
create table topics (id varchar(255) not null, description varchar(255), name varchar(255), primary key (id));
create table topics_roadmaps (topics_id varchar(255) not null, roadmaps_id varchar(255) not null);
alter table roadmap_topics add constraint FK39asjgbdqicmp8eormob4p1ci foreign key (topics_id) references topics;
alter table roadmap_topics add constraint FKoglxpajp1gdfxhs16pmbtit7c foreign key (roadmap_id) references roadmap;
alter table topics_roadmaps add constraint FK8qyvii00yltkrxrcjmp9ell03 foreign key (roadmaps_id) references roadmap;
alter table topics_roadmaps add constraint FKruw2u9r9wudttbpkmu1ko6e7s foreign key (topics_id) references topics;
create sequence hibernate_sequence start with 1 increment by 1;
create table answer (id varchar(255) not null, description varchar(255), name varchar(255), primary key (id));
create table question (id varchar(255) not null, created_at varchar(255), deleted varchar(255), description varchar(255), name varchar(255), status varchar(255), updated_at varchar(255), primary key (id));
create table roadmap (id varchar(255) not null, description varchar(255), name varchar(255), primary key (id));
create table roadmap_topics (roadmap_id varchar(255) not null, topics_id varchar(255) not null);
create table topics (id varchar(255) not null, description varchar(255), name varchar(255), primary key (id));
create table topics_roadmaps (topics_id varchar(255) not null, roadmaps_id varchar(255) not null);
alter table roadmap_topics add constraint FK39asjgbdqicmp8eormob4p1ci foreign key (topics_id) references topics;
alter table roadmap_topics add constraint FKoglxpajp1gdfxhs16pmbtit7c foreign key (roadmap_id) references roadmap;
alter table topics_roadmaps add constraint FK8qyvii00yltkrxrcjmp9ell03 foreign key (roadmaps_id) references roadmap;
alter table topics_roadmaps add constraint FKruw2u9r9wudttbpkmu1ko6e7s foreign key (topics_id) references topics;
create sequence hibernate_sequence start with 1 increment by 1;
create table answer (id varchar(255) not null, description varchar(255), name varchar(255), primary key (id));
create table question (id varchar(255) not null, created_at varchar(255), deleted varchar(255), description varchar(255), name varchar(255), status varchar(255), updated_at varchar(255), primary key (id));
create table roadmap (id varchar(255) not null, description varchar(255), name varchar(255), primary key (id));
create table roadmap_topics (roadmap_id varchar(255) not null, topics_id varchar(255) not null);
create table topic_question (topic_id varchar(255) not null, question_id varchar(255) not null);
create table topics (id varchar(255) not null, description varchar(255), name varchar(255), primary key (id));
create table topics_roadmaps (topics_id varchar(255) not null, roadmaps_id varchar(255) not null);
alter table roadmap_topics add constraint FK39asjgbdqicmp8eormob4p1ci foreign key (topics_id) references topics;
alter table roadmap_topics add constraint FKoglxpajp1gdfxhs16pmbtit7c foreign key (roadmap_id) references roadmap;
alter table topic_question add constraint FKaxy7kaoxrmprm1ulus21lbd6t foreign key (question_id) references question;
alter table topic_question add constraint FKdo9burhwi3989eh4vg76vfqe8 foreign key (topic_id) references topics;
alter table topics_roadmaps add constraint FK8qyvii00yltkrxrcjmp9ell03 foreign key (roadmaps_id) references roadmap;
alter table topics_roadmaps add constraint FKruw2u9r9wudttbpkmu1ko6e7s foreign key (topics_id) references topics;
create sequence hibernate_sequence start with 1 increment by 1;
create table answer (id varchar(255) not null, description varchar(255), name varchar(255), primary key (id));
create table question (id varchar(255) not null, created_at varchar(255), deleted varchar(255), description varchar(255), name varchar(255), status varchar(255), updated_at varchar(255), primary key (id));
create table roadmap (id varchar(255) not null, description varchar(255), name varchar(255), primary key (id));
create table roadmap_topics (roadmap_id varchar(255) not null, topics_id varchar(255) not null);
create table topic_question (topic_id varchar(255) not null, question_id varchar(255) not null);
create table topics (id varchar(255) not null, description varchar(255), name varchar(255), primary key (id));
create table topics_roadmaps (topics_id varchar(255) not null, roadmaps_id varchar(255) not null);
alter table roadmap_topics add constraint FK39asjgbdqicmp8eormob4p1ci foreign key (topics_id) references topics;
alter table roadmap_topics add constraint FKoglxpajp1gdfxhs16pmbtit7c foreign key (roadmap_id) references roadmap;
alter table topic_question add constraint FKaxy7kaoxrmprm1ulus21lbd6t foreign key (question_id) references question;
alter table topic_question add constraint FKdo9burhwi3989eh4vg76vfqe8 foreign key (topic_id) references topics;
alter table topics_roadmaps add constraint FK8qyvii00yltkrxrcjmp9ell03 foreign key (roadmaps_id) references roadmap;
alter table topics_roadmaps add constraint FKruw2u9r9wudttbpkmu1ko6e7s foreign key (topics_id) references topics;
create sequence hibernate_sequence start with 1 increment by 1;
create table answer (id varchar(255) not null, description varchar(255), name varchar(255), primary key (id));
create table question (id varchar(255) not null, created_at varchar(255), deleted varchar(255), description varchar(255), name varchar(255), status varchar(255), updated_at varchar(255), primary key (id));
create table roadmap (id varchar(255) not null, description varchar(255), name varchar(255), primary key (id));
create table roadmap_topics (roadmap_id varchar(255) not null, topics_id varchar(255) not null);
create table topic_question (topic_id varchar(255) not null, question_id varchar(255) not null);
create table topics (id varchar(255) not null, description varchar(255), name varchar(255), primary key (id));
create table topics_roadmaps (topics_id varchar(255) not null, roadmaps_id varchar(255) not null);
alter table roadmap_topics add constraint FK39asjgbdqicmp8eormob4p1ci foreign key (topics_id) references topics;
alter table roadmap_topics add constraint FKoglxpajp1gdfxhs16pmbtit7c foreign key (roadmap_id) references roadmap;
alter table topic_question add constraint FKaxy7kaoxrmprm1ulus21lbd6t foreign key (question_id) references question;
alter table topic_question add constraint FKdo9burhwi3989eh4vg76vfqe8 foreign key (topic_id) references topics;
alter table topics_roadmaps add constraint FK8qyvii00yltkrxrcjmp9ell03 foreign key (roadmaps_id) references roadmap;
alter table topics_roadmaps add constraint FKruw2u9r9wudttbpkmu1ko6e7s foreign key (topics_id) references topics;
create sequence hibernate_sequence start with 1 increment by 1;
create table answer (id varchar(255) not null, description varchar(255), name varchar(255), primary key (id));
create table question (id varchar(255) not null, created_at varchar(255), deleted varchar(255), description varchar(255), name varchar(255), status varchar(255), updated_at varchar(255), primary key (id));
create table roadmap (id varchar(255) not null, description varchar(255), name varchar(255), primary key (id));
create table roadmap_topics (roadmap_id varchar(255) not null, topics_id varchar(255) not null);
create table topic_question (topic_id varchar(255) not null, question_id varchar(255) not null);
create table topics (id varchar(255) not null, description varchar(255), name varchar(255), primary key (id));
create table topics_roadmaps (topics_id varchar(255) not null, roadmaps_id varchar(255) not null);
alter table roadmap_topics add constraint FK39asjgbdqicmp8eormob4p1ci foreign key (topics_id) references topics;
alter table roadmap_topics add constraint FKoglxpajp1gdfxhs16pmbtit7c foreign key (roadmap_id) references roadmap;
alter table topic_question add constraint FKaxy7kaoxrmprm1ulus21lbd6t foreign key (question_id) references question;
alter table topic_question add constraint FKdo9burhwi3989eh4vg76vfqe8 foreign key (topic_id) references topics;
alter table topics_roadmaps add constraint FK8qyvii00yltkrxrcjmp9ell03 foreign key (roadmaps_id) references roadmap;
alter table topics_roadmaps add constraint FKruw2u9r9wudttbpkmu1ko6e7s foreign key (topics_id) references topics;
create sequence hibernate_sequence start with 1 increment by 1;
create table answer (id varchar(255) not null, description varchar(255), name varchar(255), primary key (id));
create table question (id varchar(255) not null, created_at varchar(255), deleted varchar(255), description varchar(255), name varchar(255), status varchar(255), updated_at varchar(255), primary key (id));
create table roadmap (id varchar(255) not null, description varchar(255), name varchar(255), primary key (id));
create table roadmap_topics (roadmap_id varchar(255) not null, topics_id varchar(255) not null);
create table topic_question (topic_id varchar(255) not null, question_id varchar(255) not null);
create table topics (id varchar(255) not null, description varchar(255), name varchar(255), primary key (id));
create table topics_roadmaps (topics_id varchar(255) not null, roadmaps_id varchar(255) not null);
alter table roadmap_topics add constraint FK39asjgbdqicmp8eormob4p1ci foreign key (topics_id) references topics;
alter table roadmap_topics add constraint FKoglxpajp1gdfxhs16pmbtit7c foreign key (roadmap_id) references roadmap;
alter table topic_question add constraint FKaxy7kaoxrmprm1ulus21lbd6t foreign key (question_id) references question;
alter table topic_question add constraint FKdo9burhwi3989eh4vg76vfqe8 foreign key (topic_id) references topics;
alter table topics_roadmaps add constraint FK8qyvii00yltkrxrcjmp9ell03 foreign key (roadmaps_id) references roadmap;
alter table topics_roadmaps add constraint FKruw2u9r9wudttbpkmu1ko6e7s foreign key (topics_id) references topics;
