import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import styled, { createGlobalStyle } from "styled-components";
import StyledFooter from "../components/Footer";
import { NavBar } from "../components/NavBar";
import OpenSource from "../components/OpenSource";
import RoadCard from "../components/RoadCard";
import Wrapper from "../components/Wrapper";
import bg from "assets/background.jpg";

const Home: NextPage = () => {
  const [maxRoad, setMaxRoad] = useState(6);
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />

      <Content>
        <Wrapper>
          <h1 className="title-home">
            Bem vindo ao <span>TechQUIZ</span>
          </h1>
          <span className="description">
            Escolha um das categorias abaixo e teste seus conhecimentos sobre
            tecnologia.
          </span>

          <Cards>
            {Array(12)
              .fill(0)
              .slice(0, maxRoad)
              .map((_, index) => (
                <RoadCard key={index} title="Frontend" color="#770cf2" />
              ))}
          </Cards>

          {maxRoad == 6 && (
            <Button onClick={() => setMaxRoad(12)}>Mais Opções</Button>
          )}
        </Wrapper>
        <OpenSource />
      </Content>

      <StyledFooter />
    </Container>
  );
};

const Cards = styled.div`
  width: 100%;
  display: flex;
  flex-direction: row;
  justify-content: center;
  align-items: center;
  flex-wrap: wrap;
  gap: 96px;
`;

const Button = styled.button`
  cursor: pointer;
  width: 200px;
  height: 50px;
  color: white;
  position: relative;
  margin: auto;
  border: double 2px transparent;
  border-radius: 50px;
  background-image: linear-gradient(rgba(119, 12, 242, 0.22), #770cf2),
    radial-gradient(circle, rgba(119, 12, 242, 0.22), #770cf2 100%);
  background-origin: border-box;
  background-clip: content-box, border-box;
`;

const Content = styled.main`
  background-image: url(${bg.src});
  background-repeat: no-repeat;
  background-position: center;
  padding-top: 70px;
  color: white;
  display: flex;
  flex-direction: column;
  align-items: center;
  .wrapper {
    margin: 0 auto;
    padding: 0px 126px;
    display: flex;
    flex-direction: column;
    align-items: center;
  }

  .title-home {
    font-size: 36px;
    font-weight: 700;
    margin-bottom: 24px;
    color: #54a1ff;
    span {
      color: #770cf2;
    }
  }

  .description {
    font-size: 18px;
    margin-bottom: 48px;
  }

  ${Cards} {
    margin-top: 30px;
    margin-bottom: 40px;
  }

  ${OpenSource} {
    margin-top: 70px;
  }
`;
const Container = styled.div`
  display: flex;
  flex-direction: column;
  min-height: 100vh;
  background-color: black;
`;

export default Home;
